### ISSUE TITLE
Add Auth scheme concept?

### ISSUE THREAD

**Issue by tpluscode** [dret/sedola#30]
I was looking for a list of Authorization schemes. There is the IANA registry: http://www.iana.org/assignments/http-authschemes/http-authschemes.xhtml

Is there a good reason to duplicate that list on webconcepts? If there are other well-known schemes around, maybe so?

**Comment by dret** [comment]
On 2016-10-14 14:59, Tomasz Pluskiewicz wrote:

> I was looking for a list of Authorization schemes. There is the IANA
> registry:
> http://www.iana.org/assignments/http-authschemes/http-authschemes.xhtml
> Is there a good reason to duplicate that list on webconcepts? If there
> are other well-known schemes around, maybe so?

i don't know how this one escaped my attention so far! thanks for 
pointing it out, and i'll try to get to it asap. i think this one is 
actually a good one because supporting the same schemes is pretty 
essential for interop, so being able to surface them as a web concept is 
probably useful.

**Comment by dret** [comment]
On 2016-10-14 14:59, Tomasz Pluskiewicz wrote:

> I was looking for a list of Authorization schemes. There is the IANA
> registry:
> http://www.iana.org/assignments/http-authschemes/http-authschemes.xhtml
> Is there a good reason to duplicate that list on webconcepts? If there
> are other well-known schemes around, maybe so?

http://webconcepts.info/update/2016/10/16/adding-http-auth-schemes.html 
announces the addition of this new concept. once again, thanks for the 
suggestion. if you think that the values added so far are good enough as 
a starting point, please close the issue.

**Comment by tpluscode** [comment]
I do not have anything to add. Thanks for adding this
